### ISSUE TITLE
Can't login in site 

### ISSUE THREAD

**Issue by MaxymGorn** [CnGal/CnGalWebSite#753]
**Describe the bug**
Can't login in site in Ukraine

**To Reproduce**
1. Go to login via GitHub
2. Further login with mobile phone
3. Have that error: 
<img width="878" alt="image" src="https://github.com/CnGal/CnGalWebSite/assets/50423072/f3f9fc7f-4115-41b6-8c99-b159e2d34aa2">
I'm also try to use more standard number my Ukrainian phone number 

**Expected behavior**
I can login in site in Ukraine. In general, why I need phone number if I was authorized via GitHub? In general, other countries do not need such a Chinese authorization system through a mobile phone and so on

**Comment by LittleFish-233** [comment]
由于中国的相关法律法规，我们必须验证账号实名信息。通过手机号进行实名验证是相对方便快捷的方法。

出现这个错误是因为我们目前没有购买相海外发送短信的服务。

我们计划在本周内支持绑定海外手机号，不便之处敬请谅解。

The following is the machine translation

Due to the relevant laws and regulations in China, we must verify the real-name information of the account. Real-name verification through a mobile phone number is a relatively convenient and fast method. 

This error occurs because we do not currently have a service to send SMS messages overseas. 

We plan to support binding of overseas mobile phone numbers within this week, please forgive me for any inconvenience.

**Comment by LittleFish-233** [comment]
我们已经支持部分海外手机号码注册（包括乌克兰），但是我们无法进行完整测试以确保列表中的每个选项都工作正常。如果在注册的过程中遇到任何问题，欢迎打开issue。

The following is the machine translation

We already support some overseas mobile number registrations (including Ukraine), but we can't do a full test to make sure every option on the list is working correctly. If you encounter any problems during the registration process, you are welcome to open an issue

@MaxymGorn
